# Generated by Django 6.0.3 on 2026-03-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='created_by',
            new_name='owner',
        ),
    ]
