# Generated by Django 6.0.3 on 2026-04-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
